---

- name: "18.7.1 | PATCH | Ensure Allow Print Spooler to accept client connections is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers
      name: RegisterSpoolerRemoteRpcEndPoint
      data: 2
      type: dword
  when:
      - win10cis_rule_18_7_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.1
      - automated
      - patch
      - spooler

- name: "18.7.2 | PATCH | Ensure 'Configure Redirection Guard' is set to 'Enabled: Redirection Guard Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers
      name: RedirectionguardPolicy
      data: 1
      type: dword
  when:
      - win10cis_rule_18_7_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.2
      - automated
      - patch
      - spooler

- name: "18.7.3 | PATCH | Ensure 'Configure RPC connection settings: Protocol to use for outgoing RPC connections' is set to 'Enabled: RPC over TCP'."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC
      name: RpcUseNamedPipeProtocol
      data: 0
      type: dword
  when:
      - win10cis_rule_18_7_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.3
      - automated
      - patch
      - rpc

- name: "18.7.4 | PATCH | Ensure 'Configure RPC connection settings: Use authentication for outgoing RPC connections' is set to 'Enabled: Default'."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC
      name: RpcAuthentication
      data: 0
      type: dword
  when:
      - win10cis_rule_18_7_4
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.4
      - automated
      - patch
      - rpc

- name: "18.7.5 | PATCH | Ensure 'Configure RPC listener settings: Protocols to allow for incoming RPC connections' is set to 'Enabled: RPC over TCP'."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC
      name: RpcProtocols
      data: 5
      type: dword
  when:
      - win10cis_rule_18_7_5
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.5
      - automated
      - patch
      - rpc

- name: "18.7.6 | PATCH | Ensure 'Configure RPC listener settings: Authentication protocol to use for incoming RPC connections:' is set to 'Enabled: Negotiate' or higher."
  block:
      - name: "18.7.6 | AUDIT | Ensure 'Configure RPC listener settings: Authentication protocol to use for incoming RPC connections:' is set to 'Enabled: Negotiate' or higher. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid setting for win10cis_force_kerberos_for_rpc. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win10cis_force_kerberos_for_rpc != 0
            - win10cis_force_kerberos_for_rpc != 1

      - name: "18.7.6 | AUDIT | Ensure 'Configure RPC listener settings: Authentication protocol to use for incoming RPC connections:' is set to 'Enabled: Negotiate' or higher. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.7.6'
        when:
            - win10cis_force_kerberos_for_rpc != 0
            - win10cis_force_kerberos_for_rpc != 1

      - name: "18.7.6 | PATCH | Ensure 'Configure RPC listener settings: Authentication protocol to use for incoming RPC connections:' is set to 'Enabled: Negotiate' or higher. | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC
            name: ForceKerberosForRpc
            data: "{{ win10cis_force_kerberos_for_rpc }}"
            type: dword
        when:
            - win10cis_force_kerberos_for_rpc == 0 or win10cis_force_kerberos_for_rpc == 1
  when:
      - win10cis_rule_18_7_6
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.6
      - automated
      - patch
      - rpc

- name: "18.7.7 | PATCH | Ensure 'Configure RPC over TCP port' is set to 'Enabled: 0'."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC
      name: RpcTcpPort
      data: 0
      type: dword
  when:
      - win10cis_rule_18_7_7
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.7
      - automated
      - patch
      - rpc

- name: "18.7.8 | PATCH | Ensure 'Limits print driver installation to Administrators' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
      name: RestrictDriverInstallationToAdministrators
      data: 1
      type: dword
  when:
      - win10cis_rule_18_7_8
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.8
      - automated
      - patch
      - driver

- name: "18.7.9 | PATCH | Ensure 'Manage processing of Queue-specific files' is set to 'Enabled: Limit Queue-specific files to Color profiles'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers
      name: CopyFilesPolicy
      data: 1
      type: dword
  when:
      - win10cis_rule_18_7_9
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.9
      - automated
      - patch
      - queue

- name: "18.7.10 | PATCH | Ensure Point and Print Restrictions: When installing drivers for a new connection is set to Enabled: Show warning and elevation prompt"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint
      name: NoWarningNoElevationOnInstall
      data: 0
      type: dword
  when:
      - win10cis_rule_18_7_10
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.10
      - automated
      - patch
      - point-and-print

- name: "18.7.11 | PATCH | Ensure Point and Print Restrictions: When updating drivers for an existing connection is set to Enabled: Show warning and elevation prompt"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint
      name: UpdatePromptSettings
      data: 0
      type: dword
  when:
      - win10cis_rule_18_7_11
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.7.11
      - automated
      - patch
      - point-and-print
