- name: POST | reboot system if changes require it and not skipped
  block:
      - name: POST | Reboot system if changes require it and not skipped
        ansible.windows.win_reboot:
            reboot_timeout: 3600
        when:
            - not skip_reboot

      - name: POST | Warning a reboot required but skip option set
        ansible.builtin.debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results."
        changed_when: true
        when:
            - change_requires_reboot
            - skip_reboot

      - name: "POST | Warning a reboot required but skip option set | warning count"
        ansible.builtin.import_tasks: warning_facts.yml
        when:
            - change_requires_reboot
            - skip_reboot
  vars:
      warn_control_id: Reboot_Required
  tags:
      - always
