---

- name: "18.6.4.1 | PATCH | Ensure 'Configure NetBIOS settings' is set to 'Enabled: Disable NetBIOS name resolution on public networks'"
  block:
      - name: "18.6.4.1 | AUDIT | Ensure 'Configure NetBIOS settings' is set to 'Enabled: Disable NetBIOS name resolution on public networks'. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid setting for win10cis_enable_netbios_policy. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win10cis_enable_netbios_policy != 2
            - win10cis_enable_netbios_policy != 0

      - name: "18.6.4.1 | AUDIT | Ensure 'Configure NetBIOS settings' is set to 'Enabled: Disable NetBIOS name resolution on public networks'. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.6.4.1'
        when:
            - win10cis_enable_netbios_policy != 2
            - win10cis_enable_netbios_policy != 0

      - name: "18.6.4.1 | PATCH | Ensure 'Configure NetBIOS settings' is set to 'Enabled: Disable NetBIOS name resolution on public networks'.| Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient
            name: EnableNetbios
            data: "{{ win10cis_enable_netbios_policy }}"
            type: dword
        when: win10cis_enable_netbios_policy == 2 or win10cis_enable_netbios_policy == 0
  when:
      - win10cis_rule_18_6_4_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.6.4.1
      - automated
      - patch
      - netbios

- name: "18.6.4.2 | PATCH | Ensure Turn off multicast name resolution is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient
      name: EnableMulticast
      data: 0
      type: dword
  when:
      - win10cis_rule_18_6_4_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.6.4.2
      - automated
      - patch
      - multicast
