---

- name: "18.6.14.1 | PATCH | Ensure Hardened UNC Paths is set to Enabled with Require Mutual Authentication and Require Integrity set for all NETLOGON and SYSVOL shares"
  block:
      - name: "18.6.14.1 | PATCH | Ensure Hardened UNC Paths is set to Enabled with Require Mutual Authentication and Require Integrity set for all NETLOGON shares"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Networkprovider\Hardenedpaths
            name: "\\\\*\\NETLOGON"
            data: "RequireMutualAuthentication=1, RequireIntegrity=1, RequirePrivacy=1"
            type: string

      - name: "18.6.14.1 | PATCH | Ensure Hardened UNC Paths is set to Enabled with Require Mutual Authentication and Require Integrity set for all SYSVOL shares"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Networkprovider\Hardenedpaths
            name: "\\\\*\\SYSVOL"
            data: "RequireMutualAuthentication=1, RequireIntegrity=1, RequirePrivacy=1"
            type: string
  when: win10cis_rule_18_6_14_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.6.14.1
      - unc
