---

- name: "18.9.20.1.1 | PATCH | Ensure 'Turn off access to the Store' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer
      name: NoUseStoreOpenWith
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.1
      - internet_communication_settings
      - store

- name: "18.9.20.1.2 | PATCH | Ensure Turn off downloading of print drivers over HTTP is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Printers
      name: DisableWebPnPDownload
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.20.1.2
      - internet_communication_settings
      - drivers

- name: "18.9.20.1.3 | PATCH | Ensure Turn off handwriting personalization data sharing is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Tabletpc
      name: PreventHandwritingDataSharing
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_3
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.3
      - internet_communication_settings
      - handwriting

- name: "18.9.20.1.4 | PATCH | Ensure Turn off handwriting recognition error reporting is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Handwritingerrorreports
      name: PreventHandwritingErrorReports
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_4
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.4
      - internet_communication_settings
      - handwriting

- name: "18.9.20.1.5 | PATCH | Ensure Turn off Internet Connection Wizard if URL connection is referring to Microsoft.com is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Internet Connection Wizard
      name: ExitOnMSICW
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_5
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.5
      - internet_communication_settings
      - internet_connection_wizard

- name: "18.9.20.1.6 | PATCH | Ensure Turn off Internet download for Web publishing and online ordering wizards is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
      name: NoWebServices
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_6
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.20.1.6
      - internet_communication_settings
      - internet_downloadwizard

- name: "18.9.20.1.7 | PATCH | Ensure Turn off printing over HTTP is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Printers
      name: DisableHTTPPrinting
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_7
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.7
      - internet_communication_settings
      - printers

- name: "18.9.20.1.8 | PATCH | Ensure Turn off Registration if URL connection is referring to Microsoft.com is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Registration Wizard Control
      name: NoRegistration
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_8
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.8
      - internet_communication_settings
      - registration

- name: "18.9.20.1.9 | PATCH | Ensure Turn off Search Companion content file updates is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Searchcompanion
      name: DisableContentFileUpdates
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_9
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.9
      - internet_communication_settings
      - search

- name: "18.9.20.1.10 | PATCH | Ensure Turn off the Order Prints picture task is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
      name: NoOnlinePrintsWizard
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_10
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.10
      - internet_communication_settings
      - printers

- name: "18.9.20.1.11 | PATCH | Ensure Turn off the Publish to Web task for files and folders is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
      name: NoPublishingWizard
      data: 1
      type: dword
  when: win10cis_rule_18_9_20_1_11
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.11
      - internet_communication_settings
      - publish_to_web

- name: "18.9.20.1.12 | PATCH | Ensure Turn off the Windows Messenger Customer Experience Improvement Program is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Messenger\Client
      name: CEIP
      data: 2
      type: dword
  when: win10cis_rule_18_9_20_1_12
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.12
      - internet_communication_settings
      - mwmcei

- name: "18.9.20.1.13 | PATCH | Ensure Turn off Windows Customer Experience Improvement Program is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Sqmclient\Windows
      name: CEIPEnable
      data: 0
      type: dword
  when: win10cis_rule_18_9_20_1_13
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.13
      - internet_communication_settings
      - wmcei

- name: "18.9.20.1.14 | PATCH | Ensure Turn off Windows Error Reporting is set to Enabled"
  block:
      - name: "18.9.20.1.14 | PATCH | Ensure Turn off Windows Error Reporting is set to Enabled | Windows Error Reporting"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\Windows Error Reporting
            name: Disabled
            data: 1
            type: dword

      - name: "18.9.20.1.14 | PATCH | Ensure Turn off Windows Error Reporting is set to Enabled | ErrorReporting"
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting
            name: DoReport
            data: 0
            type: dword
  when: win10cis_rule_18_9_20_1_14
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.20.1.14
      - internet_communication_settings
      - error_reporting
