---

- name: "18.9.26.1 | PATCH | Ensure 'Allow Custom SSPs and APs to be loaded into LSASS' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\System
      name: AllowCustomSSPsAPs
      data: 0
      type: dword
  when: win10cis_rule_18_9_26_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.26.1
      - lsass

- name: "18.9.26.2 | PATCH | Ensure 'Configures LSASS to run as a protected process' is set to 'Enabled: Enabled with UEFI Lock'"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: RunAsPPL
      data: 1
      type: dword
  when: win10cis_rule_18_9_26_2
  tags:
      - level1-next-generation-windows-security
      - patch
      - automated
      - rule_18.9.26.2
      - lsass
