---

- name: "18.9.36.1 | PATCH | Ensure Enable RPC Endpoint Mapper Client Authentication is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
      name: EnableAuthEpResolution
      data: 1
      type: dword
  when: win10cis_rule_18_9_36_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.36.1
      - rpc

- name: "18.9.36.2 | PATCH | Ensure Restrict Unauthenticated RPC clients is set to Enabled Authenticated."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
      name: RestrictRemoteClients
      data: 1
      type: dword
  when: win10cis_rule_18_9_36_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.36.2
      - rpc
