---

- name: "18.9.51.1.1 | PATCH | Ensure Enable Windows NTP Client is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpclient
      name: Enabled
      data: 1
      type: dword
  when: win10cis_rule_18_9_51_1_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.51.1.1
      - time_providers
      - ntp

- name: "18.9.51.1.2 | PATCH | Ensure Enable Windows NTP Server is set to Disabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpserver
      name: Enabled
      data: 0
      type: dword
  when: win10cis_rule_18_9_51_1_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.51.1.2
      - time_providers
      - ntp
