---

- name: "18.9.35.1 | PATCH | Ensure Configure Offer Remote Assistance is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
      name: fAllowUnsolicited
      data: 0
      type: dword
  when: win10cis_rule_18_9_35_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.35.1
      - cora

- name: "18.9.35.2 | PATCH | Ensure Configure Solicited Remote Assistance is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Terminal Services
      name: fAllowToGetHelp
      data: 0
      type: dword
  when: win10cis_rule_18_9_35_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.35.2
      - csra
