---

- name: "18.9.4.1 | PATCH | Ensure Encryption Oracle Remediation is set to Enabled Force Updated Clients"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters
      name: AllowEncryptionOracle
      data: 0
      type: dword
  when: win10cis_rule_18_9_4_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.3.1
      - encryption_oracle

- name: "18.9.4.2 | PATCH | Ensure Remote host allows delegation of non-exportable credentials is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation
      name: AllowProtectedCreds
      data: 1
      type: dword
  when: win10cis_rule_18_9_4_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.4.2
      - remote_host_credentials
