---

- name: "18.9.50.1.1 | PATCH | Ensure Enable Windows NTP Client is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpclient
      name: Enabled
      data: 1
      type: dword
  when:
      - win10cis_rule_18_9_50_1_1
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.9.50.1.1
      - automated
      - patch
      - ntp

- name: "18.9.50.1.2 | PATCH | Ensure Enable Windows NTP Server is set to Disabled MS only"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpserver
      name: Enabled
      data: 1
      type: dword
  when:
      - win10cis_rule_18_9_50_1_2
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.9.50.1.2
      - automated
      - patch
      - ntp
