---

- name: "18.9.31.1 | PATCH | Ensure Allow Clipboard synchronization across devices is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\System
      name: AllowCrossDeviceClipboard
      data: 0
      type: dword
  when: win10cis_rule_18_9_31_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.31.1
      - clipboard

- name: "18.9.31.2 | PATCH | Ensure Allow upload of User Activities is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\System
      name: UploadUserActivities
      data: 0
      type: dword
  when: win10cis_rule_18_9_31_2
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.31.2
      - upload
