---

- name: "18.9.47.5.1 | PATCH | Ensure Microsoft Support Diagnostic Tool Turn on MSDT interactive communication with support provider is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Scripteddiagnosticsprovider\Policy
      name: DisableQueryRemoteServer
      data: 0
      type: dword
  when: win10cis_rule_18_9_47_5_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.47.5.1
      - microsoft_support_diagnostic_tool
      - msdt

- name: "18.9.47.11.1 | PATCH | Ensure EnableDisable PerfTrack is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Wdi\{9C5A40Da-B965-4Fc3-8781-88Dd50A6299D}
      name: ScenarioExecutionEnabled
      data: 0
      type: dword
  when: win10cis_rule_18_9_47_11_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.9.47.11.1
      - windows_performance_perftrack
      - perftrack
