---

- name: "18.4.1 | PATCH | Ensure Apply UAC restrictions to local accounts on network logons is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: LocalAccountTokenFilterPolicy
      data: 0
      type: dword
  when:
      - win10cis_rule_18_4_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.1
      - automated
      - patch
      - uac

- name: "18.4.2 | PATCH | 18.4.2 | Ensure 'Configure RPC packet level privacy setting for incoming connections' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Print
      name: RpcAuthnLevelPrivacyEnabled
      data: 1
      type: dword
  when:
      - win10cis_rule_18_4_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.2
      - automated
      - patch
      - rpc

- name: "18.4.3 | PATCH | Ensure Configure SMB v1 client driver is set to Enabled Disable driver recommended"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10
      name: Start
      data: 4
      type: dword
  when:
      - win10cis_rule_18_4_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.3
      - automated
      - patch
      - smb

- name: "18.4.4 | PATCH | Ensure Configure SMB v1 server is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
      name: SMB1
      data: 0
      type: dword
      state: present
  notify: change_requires_reboot
  when:
      - win10cis_rule_18_4_4
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.4
      - automated
      - patch
      - smb

- name: "18.4.5 | PATCH | Ensure Enable Structured Exception Handling Overwrite Protection SEHOP is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel
      name: DisableExceptionChainValidation
      data: 0
      type: dword
      state: present
  when:
      - win10cis_rule_18_4_5
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.5
      - automated
      - patch
      - sehop

- name: "18.4.6 | PATCH | Ensure 'LSA Protection' is set to 'Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: RunAsPPL
      data: 1
      type: dword
      state: present
  when:
      - win10cis_rule_18_4_5
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.6
      - automated
      - patch
      - lsa-protection

- name: "18.4.7 | PATCH | Ensure 'NetBT NodeType configuration' is set to 'Enabled: P-node recommended'"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters
      state: present
      value: NodeType
      data: "{{ win10cis_netbt_nodetype }}"
      datatype: dword
  when:
      - win10cis_rule_18_4_7
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.7
      - automated
      - patch
      - sehop

- name: "18.4.8 | PATCH | Ensure WDigest Authentication is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\Wdigest
      state: present
      value: UseLogonCredential
      data: 0
      datatype: dword
  when:
      - win10cis_rule_18_4_8
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.4.8
      - automated
      - patch
      - wdigest
