---

- name: "18.5.1 | PATCH | Ensure MSS AutoAdminLogon Enable Automatic Logon not recommended is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: AutoAdminLogon
      data: 0
      type: string
  when: win10cis_rule_18_5_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.1
      - mss_auto_logon

- name: "18.5.2 | PATCH | Ensure MSS DisableIPSourceRouting IPv6 IP source routing protection level protects against packet spoofing is set to Enabled Highest protection source routing is completely disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
      value: DisableIPSourceRouting
      data: 2
      type: dword
  when: win10cis_rule_18_5_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.2
      - iprouting

- name: "18.5.3 | PATCH | Ensure MSS DisableIPSourceRouting IP source routing protection level protects against packet spoofing is set to Enabled Highest protection source routing is completely disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: DisableIPSourceRouting
      data: 2
      type: dword
  when: win10cis_rule_18_5_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.3
      - iprouting

- name: "18.5.4 | PATCH | Ensure 'MSS: (DisableSavePassword) Prevent the dial-up password from being saved' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\RasMan\Parameters
      value: DisableSavePassword
      data: 1
      type: dword
  when: win10cis_rule_18_5_4
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.5.4
      - dial_up_password

- name: "18.5.5 | PATCH | Ensure MSS EnableICMPRedirect Allow ICMP redirects to override OSPF generated routes is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: EnableICMPRedirect
      data: 0
      type: dword
  when: win10cis_rule_18_5_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.5
      - icmp

- name: "18.5.6 | PATCH | Ensure MSS KeepAliveTime How often keep-alive packets are sent in milliseconds is set to Enabled 300000 or 5 minutes recommended"
  ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      value: KeepAliveTime
      data: 300000
      type: dword
  when: win10cis_rule_18_5_6
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.5.6
      - keepalivetime

- name: "18.5.7 | PATCH | Ensure MSS NoNameReleaseOnDemand Allow the computer to ignore NetBIOS name release requests except from WINS servers is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Netbt\Parameters
      name: NoNameReleaseOnDemand
      data: 1
      type: dword
  when: win10cis_rule_18_5_7
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.7
      - nonamereleaseondemand

- name: "18.5.8 | PATCH | Ensure MSS PerformRouterDiscovery Allow IRDP to detect and configure Default Gateway addresses could lead to DoS is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Tcpip\Parameters
      name: PerformRouterDiscovery
      data: 0
      type: dword
  when: win10cis_rule_18_5_8
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.5.8
      - irdp

- name: "18.5.9 | PATCH | Ensure MSS SafeDllSearchMode Enable Safe DLL search mode recommended is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Control\Session Manager
      name: SafeDllSearchMode
      data: 1
      type: dword
  when: win10cis_rule_18_5_9
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.9
      - safedllsearchmode

- name: "18.5.10 | PATCH | Ensure MSS ScreenSaverGracePeriod The time in seconds before the screen saver grace period expires 0 recommended is set to Enabled 5 or fewer seconds"
  block:
      - name: "18.5.10 | PATCH | Ensure MSS ScreenSaverGracePeriod The time in seconds before the screen saver grace period expires 0 recommended is set to Enabled 5 or fewer seconds | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon
            name: ScreenSaverGracePeriod
            data: "{{ win10cis_screen_saver_grace_period }}"
            type: string
        when: win10cis_screen_saver_grace_period <= 5

      - name: "18.5.10 | AUDIT | Ensure MSS ScreenSaverGracePeriod The time in seconds before the screen saver grace period expires 0 recommended is set to Enabled 5 or fewer seconds | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid time set for win10cis_screen_saver_grace_period. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_screen_saver_grace_period > 5

      - name: "18.5.10 | PATCH | Ensure MSS ScreenSaverGracePeriod The time in seconds before the screen saver grace period expires 0 recommended is set to Enabled 5 or fewer seconds | Set Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.5.10'
        when: win10cis_screen_saver_grace_period > 5
  when: win10cis_rule_18_5_10
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.10
      - screen_saver

- name: "18.5.11 | PATCH | Ensure MSS TcpMaxDataRetransmissions IPv6 How many times unacknowledged data is retransmitted is set to Enabled 3"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Tcpip6\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
  when: win10cis_rule_18_5_11
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.5.11
      - tcp_max_data_retransmissions

- name: "18.5.12 | PATCH | Ensure MSS TcpMaxDataRetransmissions How many times unacknowledged data is retransmitted is set to Enabled 3"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Services\Tcpip\Parameters
      name: TcpMaxDataRetransmissions
      data: 3
      type: dword
  when: win10cis_rule_18_5_12
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.5.12
      - tcp_max_data_retransmissions

- name: "18.5.13 | PATCH | Ensure MSS WarningLevel Percentage threshold for the security event log at which the system will generate a warning is set to Enabled 90 or less"
  block:
      - name: "18.5.13 | PATCH | Ensure MSS WarningLevel Percentage threshold for the security event log at which the system will generate a warning is set to Enabled 90 or less | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\System\Currentcontrolset\Services\Eventlog\Security
            name: WarningLevel
            data: "{{ win10cis_log_threshold_audit_event }}"
            type: dword
        when: win10cis_log_threshold_audit_event <= 90

      - name: "18.5.13 | AUDIT | Ensure MSS WarningLevel Percentage threshold for the security event log at which the system will generate a warning is set to Enabled 90 or less | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid percentage set for win10cis_log_threshold_audit_event. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_log_threshold_audit_event > 90

      - name: "18.5.13 | AUDIT | Ensure MSS WarningLevel Percentage threshold for the security event log at which the system will generate a warning is set to Enabled 90 or less | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.5.13'
        when: win10cis_log_threshold_audit_event > 90
  when: win10cis_rule_18_5_13
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.5.13
      - mss_warning_level
