---

- name: "SECTION | 18.8.1 | Notifications"
  ansible.builtin.import_tasks:
      file: cis_18.8.1.x.yml
  tags:
      - administrative-templates-computer
      - start-menu-and-taskbar
      - notifications
