---

- name: "19.7.25.1 | PATCH | Ensure Prevent users from sharing files within their profile. is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Microsoft\Windows\Currentversion\Policies\Explorer
      name: NoInplaceSharing
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  notify: change_requires_reboot
  when:
      - win10cis_rule_19_7_25_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_19.7.25.1
      - automated
      - patch
      - sharing-files
