---

- name: "19.7.40.1 | PATCH | Ensure Always install with elevated privileges is set to Disabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Installer
      name: AlwaysInstallElevated
      data: 0
      type: dword
  loop: "{{ hku_loaded_list }}"
  notify: change_requires_reboot
  when:
      - win10cis_rule_19_7_40_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_19.7.40.1
      - automated
      - patch
      - elevated-privileges
