---

- name: "SECTION | 19.1.3 | Personalization (formerly Desktop Themes)"
  ansible.builtin.import_tasks:
      file: cis_19.1.3.x.yml
  tags:
      - administrative-templates-user
      - control-panel
      - personalization

- name: "SECTION | 19.5.1 | Notifications"
  ansible.builtin.import_tasks:
      file: cis_19.5.1.x.yml
  tags:
      - administrative-templates-user
      - start-menu-and-taskbar
      - notifications

- name: "SECTION | 19.6.6 | Internet Communication Management"
  ansible.builtin.import_tasks:
      file: cis_19.6.6.x.yml
  tags:
      - administrative-templates-user
      - system
      - internet-coommuication-management

- name: "SECTION | 19.7.4 | Attachment Manager"
  ansible.builtin.import_tasks:
      file: cis_19.7.4.x.yml
  tags:
      - administrative-templates-user
      - windows-components
      - attachment-manager

- name: "SECTION | 19.7.7 | Cloud Content"
  ansible.builtin.import_tasks:
      file: cis_19.7.7.x.yml
  tags:
      - administrative-templates-user
      - windows-components
      - cloud-content

- name: "SECTION | 19.7.25 | Network Sharing"
  ansible.builtin.import_tasks:
      file: cis_19.7.25.x.yml
  tags:
      - administrative-templates-user
      - windows-components
      - network-sharing

- name: "SECTION | 19.7.40 | Windows Installer"
  ansible.builtin.import_tasks:
      file: cis_19.7.40.x.yml
  tags:
      - administrative-templates-user
      - windows-components
      - windows-installer

- name: "SECTION | 19.7.42 | Windows Media Player"
  ansible.builtin.import_tasks:
      file: cis_19.7.42.2.x.yml
  tags:
      - administrative-templates-user
      - windows-components
      - windows-media-player
