---

- name: "18.1.90.1 | PATCH | Ensure Allow Remote Shell Access is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Winrm\Service\Winrs
      name: AllowRemoteShellAccess
      data: 0
      type: dword
  when:
      - win10cis_rule_18_1_90_1
      - not win_skip_for_test
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.1.90.1
      - automated
      - patch
