---

- name: "18.10.63.1 | PATCH | Ensure Turn off KMS Client Online AVS Validation is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Nt\Currentversion\Software Protection Platform
      name: NoGenTicket
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_63_1
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.10.63.1
      - automated
      - patch
