---

- name: "18.10.72.1 | PATCH | Ensure 'Allow widgets' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Dsh
      name: AllowNewsAndInterests
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_72_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.72.1
      - automated
      - patch
