---

- name: "18.10.80.1 | PATCH | Ensure 'Allow user control over installs' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Installer
      name: EnableUserControl
      data: 0
      type: dword
  when: win10cis_rule_18_10_80_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.80.1

- name: "18.10.80.2 | PATCH | Ensure Always install with elevated privileges is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Installer
      name: AlwaysInstallElevated
      data: 0
      type: dword
  when: win10cis_rule_18_10_80_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.80.2
      - automated

- name: "18.10.80.3 | PATCH | Ensure Prevent Internet Explorer security prompt for Windows Installer scripts is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Installer
      name: SafeForScripting
      data: 0
      type: dword
  when: win10cis_rule_18_10_80_3
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.80.3
