---

- name: "18.10.66.1 | PATCH | Ensure 'Disable all apps from Microsoft Store' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: DisableStoreApps
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_66_1
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.10.66.1
      - automated
      - patch

- name: "18.10.66.2 | PATCH | Ensure 'Only display the private store within the Microsoft Store' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: RequirePrivateStoreOnly
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_66_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.66.2
      - automated
      - patch

- name: "18.10.66.3 | PATCH | Ensure 'Turn off Automatic Download and Install of updates' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: AutoDownload
      data: 4
      type: dword
  when:
      - win10cis_rule_18_10_66_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.66.3
      - automated
      - patch

- name: "18.10.66.4 | PATCH | Ensure 'Turn off the offer to update to the latest version of Windows' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: DisableOSUpgrade
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_66_4
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.66.4
      - automated
      - patch

- name: "18.10.66.5 | PATCH | Ensure 'Turn off the Store application' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\WindowsStore
      name: DisableOSUpgrade
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_66_5
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.10.66.5
      - automated
      - patch
