---
- name: "18.10.92.2.1 | PATCH | Ensure Prevent users from modifying settings is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Defender Security Center\App and Browser protection
      name: DisallowExploitProtectionOverride
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_92_2_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.92.2.1
      - automated
      - patch
      - app-and-browser-protection
