---

- name: "18.10.58.2 | PATCH | Ensure Allow Cloud Search is set to Enabled Disable Cloud Search"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
      name: AllowCloudSearch
      data: 0
      type: dword
  when: win10cis_rule_18_10_58_2
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.58.2
      - cloud_search

- name: "18.10.58.3 | PATCH | Ensure 'Allow Cortana' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
      name: AllowCortana
      data: 0
      type: dword
  when: win10cis_rule_18_10_58_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.58.3
      - cortana

- name: "18.10.58.4 | PATCH | Ensure 'Allow Cortana above lock screen' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
      name: AllowCortanaAboveLock
      data: 0
      type: dword
  when: win10cis_rule_18_10_58_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.58.4
      - cortana

- name: "18.10.58.5 | PATCH | Ensure Allow indexing of encrypted files is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
      name: AllowIndexingEncryptedStoresOrItems
      data: 0
      type: dword
  when: win10cis_rule_18_10_58_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.58.5
      - indexing

- name: "18.10.58.6 | PATCH | Ensure 'Allow search and Cortana to use location' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
      name: AllowSearchToUseLocation
      data: 0
      type: dword
  when: win10cis_rule_18_10_58_6
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.58.6
      - cortana

- name: "18.10.58.7 | PATCH | Ensure 'Allow search highlights' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
      name: EnableDynamicContentInWSB
      data: 0
      type: dword
  when: win10cis_rule_18_10_58_7
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.58.7
