---

- name: "18.10.5.1 | PATCH | Ensure Allow Microsoft accounts to be optional is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: MSAOptional
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_5_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.5.1
      - automated
      - patch

- name: "18.10.5.2 | PATCH | Ensure Allow Microsoft accounts to be optional is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
      name: BlockHostedAppAccessWinRT
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_5_2
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.10.5.2
      - automated
      - patch
      - api
