---

- name: "18.10.90.1 | PATCH | Ensure 'Allow clipboard sharing with Windows Sandbox' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Sandbox
      name: AllowClipboardRedirection
      data: 0
      type: dword
  when: win10cis_rule_18_10_90_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.90.1

- name: "18.10.90.2 | PATCH | Ensure 'Allow networking in Windows Sandbox' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Sandbox
      name: AllowNetworking
      data: 0
      type: dword
  when: win10cis_rule_18_10_90_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.90.2
