---

- name: "18.10.35.1 | PATCH | Disable Internet Explorer 11 as a standalone browser' is set to 'Enabled: Always'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Main
      name: NotifyDisableIEOptions
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_35_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.35.1
      - automated
      - patch
      - internet-explorer
