---
- name: "18.10.91.2.1 | PATCH | Ensure Prevent users from modifying settings is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows Defender Security Center\App and Browser protection
      name: DisallowExploitProtectionOverride
      data: 1
      type: dword
  when: win10cis_rule_18_10_91_2_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.91.2.1
      - app_and_browser_protection
