---

- name: "18.10.50.1 | PATCH | Ensure 'Enable news and interests on the taskbar' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Windows Feeds
      name: EnableFeeds
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_50_1
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_18.10.50.1
      - automated
      - patch
