---

- name: "18.10.76.2.1 | PATCH | Ensure 'Service Enabled' is set to 'Enabled'"
  block:
      - name: "18.10.76.2.1 | PATCH | Ensure Configure Windows Defender SmartScreen is set to Enabled Warn and prevent bypass | EnableSmartScreen"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\System
            name: EnableSmartScreen
            data: 1
            type: dword

      - name: "18.10.76.2.1 | PATCH | Ensure Configure Windows Defender SmartScreen is set to Enabled Warn and prevent bypass | ShellSmartScreenLevel"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\System
            name: ShellSmartScreenLevel
            data: Block
            type: string
  when:
      - win10cis_rule_18_10_76_2_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.76.2.1
      - automated
      - patch
      - explorer

- name: "18.10.76.3.1 | PATCH | Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: EnabledV9
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_76_3_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.76.3.1
      - automated
      - patch
      - microsoft-edge

- name: "18.10.76.3.2 | PATCH | Ensure 'Prevent bypassing Windows Defender SmartScreen prompts for sites' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\MicrosoftEdge\PhishingFilter
      name: PreventOverride
      data: 1
      type: dword
  when:
      - win10cis_rule_18_10_76_3_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.76.3.2
      - automated
      - patch
      - microsoft-edge
