---

- name: "18.10.78.1 | PATCH | Ensure 'Enables or disables Windows Game Recording and Broadcasting' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\GameDVR
      name: AllowGameDVR
      data: 0
      type: dword
  when:
      - win10cis_rule_18_10_78_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.10.78.1
      - automated
      - patch
