---

- name: "2.3.4.1 | PATCH | Ensure 'Devices: Allowed to format and eject removable media' is set to 'Administrators and Interactive Users'."
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon
      name: AllocateDASD
      data: 2
      type: string
  when:
      - win10cis_rule_2_3_4_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.3.4.1
      - automated
      - patch

- name: "2.3.4.2 | PATCH | Ensure Devices Prevent users from installing printer drivers is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Control\Print\Providers\Lanman Print Services\Servers
      name: AddPrinterDrivers
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_4_2
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_2.3.4.2
      - automated
      - patch
