---

- name: "2.3.4.1 | PATCH | Ensure Devices Prevent users from installing printer drivers is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Control\Print\Providers\Lanman Print Services\Servers
      name: AddPrinterDrivers
      data: 1
      type: dword
  when: win10cis_rule_2_3_4_1
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_2.3.4.1
