---

- name: "2.2.1 | PATCH | Ensure Access Credential Manager as a trusted caller is set to No One."
  ansible.windows.win_user_right:
      name: SeTrustedCredManAccessPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.1
      - automated
      - patch

- name: "2.2.2 | PATCH | Ensure Access this computer from the network is set to Administrators, Remote Desktop Users."
  ansible.windows.win_user_right:
      name: SeNetworkLogonRight
      users:
          - Administrators
          - Remote Desktop Users
      action: set
  when:
      - win10cis_rule_2_2_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.2
      - automated
      - patch

- name: "2.2.3 | PATCH | Ensure Act as part of the operating system is set to No One."
  ansible.windows.win_user_right:
      name: SeTcbPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.3
      - automated
      - patch

- name: "2.2.4 | PATCH | Ensure Adjust memory quotas for a process is set to Administrators, LOCAL SERVICE, NETWORK SERVICE."
  ansible.windows.win_user_right:
      name: SeIncreaseQuotaPrivilege
      users:
          - Administrators
          - Local Service
          - Network Service
      action: set
  when:
      - win10cis_rule_2_2_4
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.4
      - automated
      - patch

- name: "2.2.5 | PATCH | Ensure Allow log on locally is set to Administrators, Users."
  ansible.windows.win_user_right:
      name: SeInteractiveLogonRight
      users:
          - Administrators
          - Users
      action: set
  when:
      - win10cis_rule_2_2_5
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.5
      - automated
      - patch

- name: "2.2.6 | PATCH | Ensure Allow log on through Remote Desktop Services is set to Administrators, Remote Desktop Users."
  ansible.windows.win_user_right:
      name: SeRemoteInteractiveLogonRight
      users:
          - Administrators
          - Remote Desktop Users
      action: set
  when:
      - win10cis_rule_2_2_6
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.6
      - automated
      - patch

- name: "2.2.7 | PATCH | Ensure Back up files and directories is set to Administrators."
  ansible.windows.win_user_right:
      name: SeBackupPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_7
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.7
      - automated
      - patch

- name: "2.2.8 | PATCH | Ensure Change the system time is set to Administrators, LOCAL SERVICE."
  ansible.windows.win_user_right:
      name: SeSystemTimePrivilege
      users:
          - Administrators
          - Local Service
      action: set
  when:
      - win10cis_rule_2_2_8
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.8
      - automated
      - patch

- name: "2.2.9 | PATCH | Ensure Change the time zone is set to Administrators, LOCAL SERVICE, Users."
  ansible.windows.win_user_right:
      name: SeTimeZonePrivilege
      users:
          - Administrators
          - Local Service
          - Users
      action: set
  when:
      - win10cis_rule_2_2_9
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.9
      - automated
      - patch

- name: "2.2.10 | PATCH | Ensure Create a pagefile is set to Administrators."
  ansible.windows.win_user_right:
      name: SeCreatePagefilePrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_10
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.10
      - automated
      - patch

- name: "2.2.11 | PATCH | Ensure Create a token object is set to No One."
  ansible.windows.win_user_right:
      name: SeCreateTokenPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_11
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.11
      - automated
      - patch

- name: "2.2.12 | PATCH | Ensure Create global objects is set to Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE."
  ansible.windows.win_user_right:
      name: SeCreateGlobalPrivilege
      users:
          - Administrators
          - Local Service
          - Network Service
          - Service
      action: set
  when:
      - win10cis_rule_2_2_12
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.12
      - automated
      - patch

- name: "2.2.13 | PATCH | Ensure Create permanent shared objects is set to No One."
  ansible.windows.win_user_right:
      name: SeCreatePermanentPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_13
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.13
      - automated
      - patch

- name: "2.2.14 | PATCH | Configure Create symbolic links is set to Administrators Or Add NT VIRTUAL MACHINE when Hyper-V Installed."
  block:
      - name: "2.2.14 | PATCH | Configure Create symbolic links is set to Administrators Or Add NT VIRTUAL MACHINE when Hyper-V Installed. | No Hyper-V Installed."
        ansible.windows.win_user_right:
            name: SeCreateSymbolicLinkPrivilege
            users:
                - Administrators
            action: set
        when: "'Enabled' not in win10cis_hyper_v_installed.stdout"

      - name: "2.2.14 | PATCH | Configure Create symbolic links is set to Administrators Or Add NT VIRTUAL MACHINE when Hyper-V Installed. | Hyper-V Installed."
        ansible.windows.win_user_right:
            name: SeCreateSymbolicLinkPrivilege
            users:
                - Administrators
                - NT VIRTUAL MACHINE\Virtual Machines
            action: set
        when: "'Enabled' in win10cis_hyper_v_installed.stdout_lines"
  when:
      - win10cis_rule_2_2_14
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.14
      - automated
      - patch

- name: "2.2.15 | PATCH | Ensure Debug programs is set to Administrators."
  ansible.windows.win_user_right:
      name: SeDebugPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_15
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.15
      - automated
      - patch

- name: "2.2.16 | PATCH | Ensure Deny access to this computer from the network to include Guests."
  ansible.windows.win_user_right:
      name: SeDenyNetworkLogonRight
      users:
          - Guests
          - Local account
      action: add
  when:
      - win10cis_rule_2_2_16
      - not win_skip_for_test
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.16
      - automated
      - patch

- name: "2.2.17 | PATCH | Ensure Deny log on as a batch job to include Guests."
  ansible.windows.win_user_right:
      name: SeDenyBatchLogonRight
      users:
          - Guests
      action: add
  when:
      - win10cis_rule_2_2_17
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.17
      - automated
      - patch

- name: "2.2.18 | PATCH | Ensure Deny log on as a service to include Guests."
  ansible.windows.win_user_right:
      name: SeDenyServiceLogonRight
      users:
          - Guests
      action: add
  when:
      - win10cis_rule_2_2_18
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.18
      - automated
      - patch

- name: "2.2.19 | PATCH | Ensure Deny log on locally to include Guests."
  ansible.windows.win_user_right:
      name: SeDenyInteractiveLogonRight
      users:
          - Guests
      action: add
  when:
      - win10cis_rule_2_2_19
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.19
      - automated
      - patch

- name: "2.2.20 | PATCH | Ensure Deny log on through Remote Desktop Services to include Guests."
  ansible.windows.win_user_right:
      name: SeDenyRemoteInteractiveLogonRight
      users:
          - Guests
          - Local account
      action: add
  when:
      - win10cis_rule_2_2_20
      - not win_skip_for_test
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.20
      - automated
      - patch
      - userrights

- name: "2.2.21 | PATCH | Ensure Enable computer and user accounts to be trusted for delegation is set to No One."
  ansible.windows.win_user_right:
      name: SeEnableDelegationPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_21
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.21
      - automated
      - patch

- name: "2.2.22 | PATCH | Ensure Force shutdown from a remote system is set to Administrators."
  ansible.windows.win_user_right:
      name: SeRemoteShutdownPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_22
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.22
      - automated
      - patch
      - administrators

- name: "2.2.23 | PATCH | Ensure Generate security audits is set to LOCAL SERVICE, NETWORK SERVICE."
  ansible.windows.win_user_right:
      name: SeAuditPrivilege
      users:
          - Local Service
          - Network Service
      action: set
  when:
      - win10cis_rule_2_2_23
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.23
      - automated
      - patch
      - services

- name: "2.2.24 | PATCH | Ensure Impersonate a client after authentication is set to Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE, and when the Web Server IIS Role with Web Services Role Service is installed IIS IUSRS."
  block:
      - name: "2.2.24 | AUDIT | Ensure Impersonate a client after authentication is set to Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE, and when the Web Server IIS Role with Web Services Role Service is installed IIS IUSRS. | Check IIS-WebServerRole"
        ansible.windows.win_shell: Get-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole | Select-Object -Property State | ft -hide
        changed_when: false
        failed_when: false
        register: win10cis_iis_web_server_role_installed

      - name: "2.2.24 | PATCH | Ensure Impersonate a client after authentication is set to Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE, and when the Web Server IIS Role with Web Services Role Service is installed IIS IUSRS. | Web Server Not Installed."
        ansible.windows.win_user_right:
            name: SeImpersonatePrivilege
            users:
                - Administrators
                - Local Service
                - Network Service
                - Service
            action: set
        when: "'Enabled' not in win10cis_iis_web_server_role_installed.stdout_lines"

      - name: "2.2.24 | PATCH | Ensure Impersonate a client after authentication is set to Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE, and when the Web Server IIS Role with Web Services Role Service is installed IIS IUSRS. | Web Server Installed."
        ansible.windows.win_user_right:
            name: SeImpersonatePrivilege
            users:
                - Administrators
                - IIS_IUSRS
                - Local Service
                - Network Service
                - Service
            action: set
        when: "'Enabled' in win10cis_iis_web_server_role_installed.stdout_lines"
  when:
      - win10cis_rule_2_2_24
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.24
      - automated
      - patch
      - administrators

- name: "2.2.25 | PATCH | Ensure Increase scheduling priority is set to Administrators, Window Manager/Window Manager Group."
  ansible.windows.win_user_right:
      name: SeIncreaseBasePriorityPrivilege
      users:
          - Administrators
          - Window Manager\Window Manager Group
      action: set
  when:
      - win10cis_rule_2_2_25
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.25
      - automated
      - patch
      - administrators

- name: "2.2.26 | PATCH | Ensure Load and unload device drivers is set to Administrators."
  ansible.windows.win_user_right:
      name: SeLoadDriverPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_26
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.26
      - automated
      - patch
      - administrators

- name: "2.2.27 | PATCH | Ensure Lock pages in memory is set to No One."
  ansible.windows.win_user_right:
      name: SeLockMemoryPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_27
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.27
      - automated
      - patch
      - administrators

- name: "2.2.28 | PATCH | Ensure Log on as a batch job is set to Administrators."
  ansible.windows.win_user_right:
      name: SeBatchLogonRight
      users: "{{ win10cis_sebatchlogonright }}"
      action: set
  when:
      - win10cis_rule_2_2_28
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_2.2.28
      - automated
      - patch
      - administrators

- name: "2.2.29 | PATCH | Configure Log on as a service."
  block:
      - name: "2.2.29 | PATCH | Configure Log on as a service. | Hyper-V not installed."
        ansible.windows.win_user_right:
            name: SeServiceLogonRight
            users: "{{ win10cis_sebatchlogonright }}"
            action: set
        when:
            - "'Enabled' not in win10cis_hyper_v_installed.stdout"
            - '"" in win10cis_sebatchlogonright'

      - name: "2.2.29 | PATCH | Configure Log on as a service. | Hyper-V installed."
        ansible.windows.win_user_right:
            name: SeServiceLogonRight
            users:
                - NT VIRTUAL MACHINE\Virtual Machines
            action: set
        when:
            - "'Enabled' in win10cis_hyper_v_installed.stdout"
            - '"" in win10cis_sebatchlogonright'

      - name: "2.2.29 | PATCH | Configure Log on as a service. | User Defined Input."
        ansible.windows.win_user_right:
            name: SeServiceLogonRight
            users: "{{ win10cis_sebatchlogonright }}"
            action: set
        when:
            - '"" not in win10cis_sebatchlogonright'
  when:
      - win10cis_rule_2_2_29
  tags:
      - level2-high-security-sensitive-data-environment
      - rule_2.2.29
      - automated
      - patch

- name: "2.2.30 | PATCH | Ensure Manage auditing and security log is set to Administrators."
  ansible.windows.win_user_right:
      name: SeSecurityPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_30
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.30
      - automated
      - patch
      - administrators

- name: "2.2.31 | PATCH | Ensure Modify an object label is set to No One."
  ansible.windows.win_user_right:
      name: SeReLabelPrivilege
      users: []
      action: set
  when:
      - win10cis_rule_2_2_31
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.31
      - automated
      - patch

- name: "2.2.32 | PATCH | Ensure Modify firmware environment values is set to Administrators."
  ansible.windows.win_user_right:
      name: SeSystemEnvironmentPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_32
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.32
      - automated
      - patch
      - administrators

- name: "2.2.33 | PATCH | Ensure Perform volume maintenance tasks is set to Administrators."
  ansible.windows.win_user_right:
      name: SeManageVolumePrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_33
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.33
      - automated
      - patch
      - administrators

- name: "2.2.34 | PATCH | Ensure Profile single process is set to Administrators."
  ansible.windows.win_user_right:
      name: SeProfileSingleProcessPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_34
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.34
      - automated
      - patch
      - administrators

- name: "2.2.35 | PATCH | Ensure Profile system performance is set to Administrators, NT SERVICE\\WdiServiceHost."
  ansible.windows.win_user_right:
      name: SeSystemProfilePrivilege
      users:
          - Administrators
          - NT SERVICE\WdiServiceHost
      action: set
  when:
      - win10cis_rule_2_2_35
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.35
      - automated
      - patch
      - administrators
      - service

- name: "2.2.36 | PATCH | Ensure Replace a process level token is set to LOCAL SERVICE, NETWORK SERVICE."
  ansible.windows.win_user_right:
      name: SeAssignPrimaryTokenPrivilege
      users:
          - LOCAL SERVICE
          - NETWORK SERVICE
      action: set
  when:
      - win10cis_rule_2_2_36
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.36
      - automated
      - patch
      - service

- name: "2.2.37 | PATCH | Ensure Restore files and directories is set to Administrators."
  ansible.windows.win_user_right:
      name: SeRestorePrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_37
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.37
      - automated
      - patch
      - administrators

- name: "2.2.38 | PATCH | Ensure Shut down the system is set to Administrators, Users."
  ansible.windows.win_user_right:
      name: SeShutdownPrivilege
      users:
          - Administrators
          - Users
      action: set
  when:
      - win10cis_rule_2_2_38
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.38
      - automated
      - patch
      - administrators

- name: "2.2.39 | PATCH | Ensure Take ownership of files or other objects is set to Administrators"
  ansible.windows.win_user_right:
      name: SeTakeOwnershipPrivilege
      users:
          - Administrators
      action: set
  when:
      - win10cis_rule_2_2_39
  tags:
      - level1-corporate-enterprise-environment
      - rule_2.2.39
      - automated
      - patch
      - administrators
