---

- name: "2.3.15.1 | PATCH | Ensure System objects Require case insensitivity for non-Windows subsystems is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Control\Session Manager\Kernel
      name: ObCaseInsensitive
      data: 1
      type: dword
  when: win10cis_rule_2_3_15_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.15.1

- name: "2.3.15.2 | PATCH | Ensure System objects Strengthen default permissions of internal system objects e.g. Symbolic Links is set to Enabled."
  ansible.windows.win_regedit:
      path: HKLM:\System\Currentcontrolset\Control\Session Manager
      name: ProtectionMode
      data: 1
      type: dword
  when:
      - win10cis_rule_2_3_15_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_2.3.15.2
