---

- name: "18.1.1.1 | PATCH | Ensure Prevent enabling lock screen camera is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
      name: NoLockScreenCamera
      data: 1
      type: dword
  when:
      - win10cis_rule_18_1_1_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.1.1.1
      - automated
      - patch
      - lock-screen-camera

- name: "18.1.1.2 | PATCH | Ensure Prevent enabling lock screen slide show is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
      name: NoLockScreenSlideshow
      data: 1
      type: dword
  when:
      - win10cis_rule_18_1_1_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.1.1.2
      - automated
      - patch
      - lock-screen-slideshow
