---

- name: "SECTION | 18.1.1 | Personalization"
  ansible.builtin.import_tasks:
      file: cis_18.1.1.x.yml
  tags:
      - administrative-templates-computer
      - control-panel
      - personalization

- name: "SECTION | 18.1.2 | Regional And Language Options"
  ansible.builtin.import_tasks:
      file: cis_18.1.2.x.yml
  tags:
      - administrative-templates-computer
      - control-panel
      - regional-and-language-options

- name: "SECTION | 18.1.3 | Online Tips"
  ansible.builtin.import_tasks:
      file: cis_18.1.3.x.yml
  tags:
      - administrative-templates-computer
      - control-panel
      - regional-and-language-options
