---

- name: "18.3.1 | PATCH | Ensure LAPS AdmPwd GPO Extension CSE is installed."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\GPExtensions\{D76B9641-3288-4f75-942D-087DE603E3EA}
      name: DllName
      data: C:\Program Files\LAPS\CSE\AdmPwd.dll
      type: string
  when:
      - win10cis_rule_18_3_1
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.3.1
      - automated
      - patch
      - gpo

- name: "18.3.2 | PATCH | Ensure Do not allow password expiration time longer than required by policy is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd
      name: PwdExpirationProtectionEnabled
      data: 1
      type: dword
  when:
      - win10cis_rule_18_3_2
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.3.2
      - automated
      - patch
      - password

- name: "18.3.3 | PATCH | Ensure Enable Local Admin Password Management is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd
      name: AdmPwdEnabled
      data: 1
      type: dword
  when:
      - win10cis_rule_18_3_3
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.3.3
      - automated
      - patch
      - administrator-password

- name: "18.3.4 | PATCH | Ensure Password Settings Password Complexity is set to Enabled Large letters small letters numbers special characters."
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd
      name: PasswordComplexity
      data: 4
      type: dword
  when:
      - win10cis_rule_18_3_4
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.3.4
      - automated
      - patch
      - password

- name: "18.3.5 | PATCH | Ensure Password Settings Password Length is set to Enabled 15 or more."
  block:
      - name: "18.3.5 | AUDIT | Ensure Password Settings Password Length is set to Enabled 15 or more MS only. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid password length set for win10cis_laps_password_length please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_laps_password_length < 15

      - name: "18.3.5 | AUDIT | Ensure Password Settings Password Length is set to Enabled 15 or more MS only. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.3.5'
        when: win10cis_laps_password_length < 15

      - name: "18.3.5 | PATCH | Ensure Password Settings Password Length is set to Enabled 15 or more MS only. | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd
            name: PasswordLength
            data: "{{ win10cis_laps_password_length }}"
            type: dword
        when: win10cis_laps_password_length >= 15
  when:
      - win10cis_rule_18_3_5
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.3.5
      - patch
      - password

- name: "18.3.6 | PATCH | Ensure Password Settings Password Age Days is set to Enabled 30 or fewer."
  block:
      - name: "18.3.6 | AUDIT | Ensure Password Settings Password Age Days is set to Enabled 30 or fewer MS only | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid password length set for win10cis_laps_password_length please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win10cis_laps_password_age_days > 30

      - name: "18.3.6 | AUDIT | Ensure Password Settings Password Age Days is set to Enabled 30 or fewer MS only | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.3.6'
        when: win10cis_laps_password_age_days > 30

      - name: "18.3.6 | PATCH | Ensure Password Settings Password Age Days is set to Enabled 30 or fewer MS only | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft Services\AdmPwd
            name: PasswordAgeDays
            data: "{{ win10cis_laps_password_age_days }}"
            type: dword
        when: win10cis_laps_password_age_days <= 30
  when:
      - win10cis_rule_18_3_6
  tags:
      - level1-corporate-enterprise-environment
      - rule_18.3.6
      - automated
      - patch
      - password
