---

- name: "SECTION | 9.1 | Domain Profile"
  ansible.builtin.import_tasks:
      file: cis_9.1.x.yml
  tags:
      - windows-defender-firewall-with-advanced-security
      - domain-profile

- name: "SECTION | 9.2 | Private Profile"
  ansible.builtin.import_tasks:
      file: cis_9.2.x.yml
  tags:
      - windows-defender-firewall-with-advanced-security
      - private-profile

- name: "SECTION | 9.3 | Public Profile"
  ansible.builtin.import_tasks:
      file: cis_9.3.x.yml
  tags:
      - windows-defender-firewall-with-advanced-security
      - public-profile
